name: SonarCloud analysis

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Analyze with SonarCloud

        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=MathiasReker_php-chmod
            -Dsonar.organization=mathiasreker
            -Dsonar.sources=src
            -Dsonar.projectBaseDir=.
            -Dsonar.tests=tests
            -Dsonar.verbose=true
            -Dsonar.sourceEncoding=UTF-8
